# Create a minimal Ubuntu box
Vagrant.require_version ">= 2.1.2"
Vagrant.configure(2) do |config|

    # Configure the base box
    config.vm.define "centos/7" do |centos|

        # Find the latest images on https://app.vagrantup.com/ubuntu
        centos.vm.box = "centos/7"

        centos.vm.hostname = "elastic-stack"

        centos.vm.network :forwarded_port, guest: 8080, host: 8080

        # If you export the box switch to the second line to keep the /elastic-stack/ folder
        centos.vm.synced_folder "elastic-stack/", "/elastic-stack/"
        #centos.vm.synced_folder "elastic-stack/", "/elastic-stack/", type: "rsync"
    end
   #Autenticación del usuario 
  	config.ssh.username = 'challange'

    # Configure the VirtualBox parameters
    config.vm.provider "virtualbox" do |vb|
        vb.name = "elastic-stack"
        vb.customize [ "modifyvm", :id, "--memory", "3072" ]
    end
#troubleshouting en kvm descomentar
#    config.vm.provider "libvirt" do | libvirt |

#      libvirt.driver = "qemu"   
#       end

    # Configure the box with Ansible
    config.vm.provision "ansible_local" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "/elastic-stack/0_install.yml"
    end


end
